### PR TITLE
Add Facebook share button

### PR DESCRIPTION
**Pull request by jlegrone**
- Adds a sticky share-controls div containing a Facebook share button. Alternate sharing controls can be switched out.
- Makes footer float over sidebar

View changes at https://jacoblegrone.com/i-like-bernie-but

### CODE REVIEW

**Comment by jacobnisnevich** [comment]
Oh I just addressed this issue in #7

**Comment by jlegrone** [comment]
Yeah I saw that, if you want to still use this and swap in your share controls that would give you a nice sticky div in the bottom right that follows the footer when you scroll to the bottom. Or merge yours and I can amend.

**Comment by jacobnisnevich** [comment]
Ok I think I'll merge my changes and add the footer style you made then?

**Comment by jlegrone** [comment]
Sure, I'll send a new PR in a bit.

**Pull request closed without merging**
