### PR TITLE
Make social links sticky, update sidebar style, add hash support

### PR DESCRIPTION
**Pull request by jlegrone**
- Social links are now visible in the bottom right at all times on desktop, and in the footer on mobile
- Changed to a light sidebar theme to contrast with header and footer
- Sidebar automatically minimizes to the left when scrolled to bottom of page
- Clicking sidebar items populates hash with current question for sharing purposes
  - [jlegrone.github.io/i-like-bernie-but/#how-old-is-he-again?](http://jlegrone.github.io/i-like-bernie-but/#how-old-is-he-again?)

View changes here: [jlegrone.github.io/i-like-bernie-but](http://jlegrone.github.io/i-like-bernie-but)

### CODE REVIEW

**Comment by jacobnisnevich** [comment]
I like the changes. Do you think the share controls stand out enough in white in front of the grey background?

**Comment by jlegrone** [comment]
I think so. I like the subtlety, though they are definitely visible. And when you scroll to the bottom they are still placed over the blue background.

**Comment by jacobnisnevich** [comment]
Oh I was working on question ids too. You think you can switch to the ids I have [here](https://github.com/jacobnisnevich/i-like-bernie-but/blob/question-ids/js/faq.js)? I think they are a little more concise

**Comment by jlegrone** [comment]
Ah shoot. I was thinking that the ids should be more idiomatic, so it is clear what question the link is answering. For example, [ilikeberniebut.com/#is-he-electable?](https://jacoblegrone.com/i-like-bernie-but/#is-he-electable?) vs [ilikeberniebut.com/#electable](https://jacoblegrone.com/i-like-bernie-but/#is-he-electable?)

**Comment by jacobnisnevich** [comment]
I guess both arguments could be made. What do you think @AlexNisnevich?

**Comment by AlexNisnevich** [comment]
I think either would be fine. I do like @jlegrone 's idea of idiomatic ids.

**Pull request merged**
