### PR TITLE
Add animation to conversation thread elements

### PR DESCRIPTION
**Pull request by celsom3**
Used wow.js and animate.css to add animations as the user scrolls. Just
added classes to .question-container and .answer-container divs.

### CODE REVIEW

**Comment by celsom3** [comment]
You can preview the changes here: [celsom3.github.io/i-like-bernie-but/](celsom3.github.io/i-like-bernie-but/)

**Comment by jacobnisnevich** [comment]
Have you tested it on mobile? It does a weird zoom when you scroll down to a new question on my phone.

**Comment by AlexNisnevich** [comment]
Is it possible to just disable the animations on mobile, perhaps?

**Comment by celsom3** [comment]
Looking into it. I see what you mean.

**Comment by celsom3** [comment]
Fixed the issue. I followed your advice and just disabled it on mobile. Probably for the best anyways, since some mobile devices can have problems with animations.

**Comment by jlegrone** [comment]
There is a whole lot of movement here. Perhaps use only opacity transitions or decrease the initial lateral offsets?

**Comment by celsom3** [comment]
Got it. I went ahead and make it a simple fadeIn animation.

**Comment by celsom3** [comment]
Not sure if the commits I've been making after the pull request are 'mergable' from this pull request (semi-noob here). Let me know if it would be easier to submit a new pull request with suggested changes. Thanks :+1:

**Comment by AlexNisnevich** [comment]
It's all mergeable from here, but the tabs-to-spaces thing makes the diff really messy. Could you convert back to tabs, since that's how the JS file was formatted before? It would just make things a little clearer.

**Comment by celsom3** [comment]
Sorry about that. I must have run a linter or beautify script. I'll figure out how to revert back.

**Pull request closed without merging**
